# 相关文档：
#    了解 GitHub Action     https://docs.github.com/cn/actions/learn-github-actions/understanding-github-actions
#    构建和测试 Node.js     https://docs.github.com/cn/actions/automating-builds-and-tests/building-and-testing-nodejs
#    搜索公开的Action       https://github.com/marketplace?type=actions
#
# 引用变量注意事项
#   (1) 通常情况下引用变量方式，比如run指令中
#         ${var}
#   (2) 其他情况下的引用变量方式，比如引用secret变量、给action传参等
#         ${{ env.变量名 }}

name: deploy
on:                   
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:

  build:  
    runs-on: ubuntu-latest    
    env:
      imageName: note
      imageTag: latest      
      containerName: jinhui.dev

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
        
      - name: 构建镜像并导出
        run: |
          docker build . --file Dockerfile --tag ${imageName}:${imageTag}
          docker image save ${imageName}:${imageTag} -o ${imageName}-${imageTag}.tar

      # https://github.com/marketplace/actions/scp-command-to-transfer-files
      - name: 拷贝镜像到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ${{ env.imageName }}-${{ env.imageTag }}.tar
          target: /tmp/

      # https://github.com/marketplace/actions/ssh-remote-commands
      - name: 服务器导入镜像
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker image load -i /tmp/${{ env.imageName }}-${{ env.imageTag }}.tar

      - name: 服务器重启容器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker container inspect ${{ env.containerName }} &>/dev/null && docker container rm -f ${{ env.containerName }}
            docker container run --name ${{ env.containerName }} -p80:80 -p443:443 --restart always --cpus 1.0 --memory 1g -d ${{ env.imageName }}:${{ env.imageTag }}

      - name: 服务器清理资源
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            rm -vf /tmp/${{ env.imageName }}-${{ env.imageTag }}.tar
            docker image prune -f
